"""empty message

Revision ID: 1d74ed5fe8c5
Revises: cb01a1b66162
Create Date: 2023-06-07 22:34:10.835582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d74ed5fe8c5'
down_revision = 'cb01a1b66162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_id', sa.String(length=64)))
        batch_op.create_unique_constraint('model_social_id_key', ['social_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('model_social_id_key', type_='unique')
        batch_op.drop_column('social_id')

    # ### end Alembic commands ###
