"""empty message

Revision ID: 692aad0f317a
Revises: 34b78ba777d1
Create Date: 2023-04-09 16:06:44.636435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692aad0f317a'
down_revision = '34b78ba777d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
