"""empty message

Revision ID: e12abd3b5fa2
Revises: 
Create Date: 2023-03-21 22:35:19.783920

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e12abd3b5fa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('things',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('shop_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('things')
    op.drop_table('shops')
    # ### end Alembic commands ###
