"""empty message

Revision ID: ecf7ef0ee669
Revises: 1d74ed5fe8c5
Create Date: 2023-06-07 23:46:01.980246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf7ef0ee669'
down_revision = '1d74ed5fe8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('token', sa.String(length=256), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')
        batch_op.drop_constraint('model_social_id_key', type_='unique')
        batch_op.create_unique_constraint('username_key', ['username'])
        batch_op.create_unique_constraint('token_key', ['token'])
        batch_op.create_unique_constraint('user_id_key', ['user_id'])
        batch_op.drop_column('social_id')
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('social_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('model_social_id_key', ['social_id'])
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('token')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
